blank_issues_enabled: false

contact_links:
  - name: Common Issues [TBA]
    url: https://openmim.readthedocs.io/en/latest/faq.html
    about: Check if your issue already has solutions
  - name: MIM Documentation
    url: https://openmim.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
